### ISSUE TITLE
Unable to load websocket-sharp.dll if ADOFAI is in a different path

### ISSUE THREAD

**Issue by ppapman1** [thijnmens/AdofaiWeb#2]
```cs
        internal static void Load(UnityModManager.ModEntry modEntry)
        {
            LoadAssembly("C:/Program Files (x86)/Steam/steamapps/common/A Dance of Fire and Ice/A Dance of Fire and Ice_Data/Managed/websocket-sharp.dll");

            Main.Setup(modEntry);
        }
```
[AdofaiWeb/Startup.cs:13](https://github.com/thijnmens/AdofaiWeb/blob/4a526e9e5c914b74a48ac5e44b5ccc953310fafd/AdofaiWeb/Startup.cs#L13)

This code can't load the DLL if ADOFAI is not on drive C or if the steam folder name is not "Steam."
(like `E:/SteamLibrary/steamapps/common/A Dance of Fire and Ice/`)

**Comment by ppapman1** [comment]
The link of log https://cdn.discordapp.com/attachments/886661630304350208/985035385577037884/Player.txt

**Comment by thijnmens** [comment]
This is fine, the loadAssembly doesnt do shit yet sadly. I had my own path in there for debugging purposes, but i could not get it to work, i forgot to comment it out. If you do know how to load an assembly from a folder that's not the managed folder please do make a PR for that

**Comment by thijnmens** [comment]
I did a bit more research and found why it wasn't working, now that that's fixed I'll update the path to accommodate any install folder

**Comment by thijnmens** [comment]
was fixed a while ago i think
